### PR TITLE
ft(signup): user signup

### PR DESCRIPTION
**Pull request by Emile-Nsengimana**
#### What does this PR do?
 - allows a new user to signup
 - open home screen after successful signup

#### Description of Task to be completed?
As a new user, I want to be able to signup so that I can make an order or navigate different resto and hotels
##### Acceptance criteria
- I can sign-up with a username
- I can sign-up with a phone number
- I can sign up by email 

#### How should this be manually tested?

- Clone the project through your terminal(VScode terminal)

      git clone https://github.com/Volve-gitore/quickss-frontend.git

- Open the project using your favorite IDE

- Change the branch

       git checkout ft-signup-QUIC-29

- Run the app(and scan the QR code with your phone or use android studio emulator)
``` yarn start```

#### Any background context you want to provide?
 - please change the `IP address` in `src/utils/api` to your specific IP
 - your backend server should be running

#### What are the relevant Jira story?

[QUIC-29](https://quickss.atlassian.net/browse/QUIC-29)

#### Screenshots (if appropriate)
WhatsApp Image 2020-11-09 at 11 07 21

### CODE REVIEW

**Review by Kagorora — APPROVED** [review]
Well done

**Review by BlaiseJavan — APPROVED** [review]
You have done a great job on this but one thing you should change a bit is the responsiveness. let me show you how it looks on my phone.



the background image doesn't cover all the page.

**Comment by Emile-Nsengimana** [comment]
Thanks for spotting that, am on it

**Comment by Emile-Nsengimana** [comment]
> You have done a great job on this but one thing you should change a little bit is the responsiveness. let me show you how it looks on my phone.
>
> 
> the background image doesn't cover all the page.

Thanks for spotting that, am on it.

**Pull request merged**
