### PR TITLE
ch(auth screens): re-design login and signup

### PR DESCRIPTION
**Pull request by Emile-Nsengimana**
#### What does this PR do?
 - re-design sign in and sign up screens

#### Description of Task to be completed?
 - new user should be able to signup with phoneNo, full name and password
 - registered user should be able to login with phoneNo and password

##### Acceptance criteria
       - I should be able to signup with phoneNo and fullname
       - I should be able to login with phoneNo and password

#### How should this be manually tested?

- Clone the project through your terminal(VScode terminal)

      git clone https://github.com/Volve-gitore/quickss-frontend.git

- Open the project using your favorite IDE

- Change the branch

       git checkout rf-change-authentication-screens-QUIC-45

- Run the app(and scan the QR code with your phone or use android studio emulator)
``` yarn start```

#### Any background context you want to provide?
 - please change the `IP address` in `src/utils/api` to your specific IP
 - your backend server should be running
 - this changes correspond to changes in `rf-authentication-QUIC-45` branch on `back-end`(make sure to checkout this branch)

#### What are the relevant Jira story?

[QUIC-45](https://quickss.atlassian.net/browse/QUIC-45)

### CODE REVIEW

**Review by BlaiseJavan — APPROVED** [review]
Great job! you designed it as expected.

**Comment by Emile-Nsengimana** [comment]
> Great job! you designed it as expected but you put +250 on the field of phone number, what if the phone number is not Rwandan? will the user be able to choose another code?

yes the user can still change the code

**Comment by BlaiseJavan** [comment]
> > Great job! you designed it as expected but you put +250 on the field of phone number, what if the phone number is not Rwandan? will the user be able to choose another code?
> 
> yes the user can still change the code

Cool

**Review by Kagorora — APPROVED** [review]
Good Job @Emile-Nsengimana

**Pull request merged**
